services:
  - type: web
    name: heart-disease-backend
    env: docker
    dockerfilePath: ./backend.Dockerfile
    autoDeployOnPush: true
    healthCheckPath: /health
    envVars:
      - key: API_HOST
        value: 0.0.0.0
      - key: API_PORT
        value: 8000
      - key: PYTHONUNBUFFERED
        value: 1

  - type: web
    name: heart-disease-frontend
    env: docker
    dockerfilePath: ./frontend.Dockerfile
    autoDeployOnPush: true
    healthCheckPath: /_stcore/health
    envVars:
      - key: STREAMLIT_SERVER_PORT
        value: 8501
      - key: STREAMLIT_SERVER_ADDRESS
        value: 0.0.0.0
      - key: STREAMLIT_SERVER_HEADLESS
        value: true
      - key: API_URL
        fromService:
          name: heart-disease-backend
          property: url
